language: php

php:
    #- 5.4
    #- 5.5
    - 5.6
    #- hhvm
    #- nightly
    #- "7.0"



sudo: false



git:
    submodules: true



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck


matrix:
    allow_failures:
        - php: hhvm
        - php: nightly



before_script:

    # Create a build directory for output
    # Store all files in your own bin
    #- install --directory build/bin
    #- export PATH=$PATH:$PWD/build/bin/

    # Install validation tools
    #- npm install -g htmlhint csslint jshint jscs jsonlint js-yaml html-minifier@0.8.0 clean-css uglify-js
    - make npm-install



script:
    # Check versions of validation tools
    #- node --version
    #- npm --version
    
    #- htmlhint --version
    #- csslint --version
    #- jscs --version
    #- jshint --version
    #- phpcs --version
    #- phpmd --version
    #- jsonlint --version
    #- js-yaml --version
    #- shellcheck --version
    
    #- html-minifier --version
    #- cleancss --version
    #- uglifyjs --version
    
    - lessc --version
    - csslint --version
    
    # Run validation & publish
    #- composer validate
    - make test
    #- make phpcs



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
          - https://webhooks.gitter.im/e/f8ada0423bd8013636a8
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
